### ISSUE TITLE
Support pytest.skip()

### ISSUE THREAD

**Issue by gasparka** [computationalmodelling/nbval#101]
This is the standard way to skip in pytest and i my opinion superior to # NBVAL_SKIP. 
For example if i only want to skip the cell in CI i could write:
```python
if  'TRAVIS' in os.environ:
    pytest.skip()
```
I could work on a PR if there is interest in pulling this in.

**Comment by takluyver** [comment]
It feels awkward to me. The design of nbval is that you're writing normal notebooks and validating that they still run. I want to minimise the extent that you change your notebooks to fit around this check, and importing pytest in the notebook is a pretty conspicuous change.

**Comment by gasparka** [comment]
My motivation for this feature is the ability to skip a cell conditionally.
Situation is that i have a cell that requires dependencies not usable on CI. So i would like to skip it, but only if the dependency is not available. 
Any alternative ideas on how to achieve this?

**Comment by gasparka** [comment]
I think i dont need this afterall, good call :)

**Comment by takluyver** [comment]
OK,  thanks!
