### ISSUE TITLE
coverage report should use package relative path instead of absolute path

### ISSUE THREAD

**Issue by utensil** [computationalmodelling/nbval#103]
Before adding nbval, the test command was like:

```bash
pytest --cov=galgebra test
```

it outputs:

```
----------- coverage: platform win32, python 3.6.2-final-0 -----------
Name                   Stmts   Miss  Cover
------------------------------------------
galgebra\__init__.py       0      0   100%
galgebra\ga.py          1116    415    63%
galgebra\lt.py           594    529    11%
galgebra\metric.py       481    219    54%
galgebra\mv.py          1815   1142    37%
galgebra\printer.py      914    639    30%
galgebra\setgapth.py      25     25     0%
galgebra\utils.py         11      6    45%
------------------------------------------
TOTAL                   4956   2975    40%
```
After adding nbval, the test command was like:

```
pytest --cov=galgebra --nbval examples/ipython/dop.ipynb --current-env test
```
it outputs:

```
----------- coverage: platform win32, python 3.6.2-final-0 -----------
Name                                                   Stmts   Miss  Cover
--------------------------------------------------------------------------
E:\Miniconda3\Lib\site-packages\galgebra\__init__.py       0      0   100%
E:\Miniconda3\Lib\site-packages\galgebra\ga.py          1116    654    41%
E:\Miniconda3\Lib\site-packages\galgebra\lt.py           594    529    11%
E:\Miniconda3\Lib\site-packages\galgebra\metric.py       481    274    43%
E:\Miniconda3\Lib\site-packages\galgebra\mv.py          1815   1083    40%
E:\Miniconda3\Lib\site-packages\galgebra\printer.py      914    573    37%
E:\Miniconda3\Lib\site-packages\galgebra\setgapth.py      25     25     0%
E:\Miniconda3\Lib\site-packages\galgebra\utils.py         11      6    45%
galgebra\__init__.py                                       0      0   100%
galgebra\ga.py                                          1116    415    63%
galgebra\lt.py                                           594    529    11%
galgebra\metric.py                                       481    219    54%
galgebra\mv.py                                          1815   1142    37%
galgebra\printer.py                                      914    639    30%
galgebra\setgapth.py                                      25     25     0%
galgebra\utils.py                                         11      6    45%
--------------------------------------------------------------------------
TOTAL                                                   9912   6119    38%
```

which is not desired.

**Comment by vidartf** [comment]
Which directory were you in when you ran that command? Do you have two concurrent installs of `galgebra`? If your `dop.ipynb` runs `import galgebra`, you will need to ensure that you have a development install of your package (e.g. `pip install -e .`).

**Comment by utensil** [comment]
> Which directory were you in when you ran that command?

The root of repository https://github.com/pygae/galgebra



> Do you have two concurrent installs of `galgebra`?

Only a `pip install .` (both in local environment and CI)



> If your `dop.ipynb` runs `import galgebra`

`dop.ipynb` does run `import galgebra` just like the tests. I believe they will run the same code installed to site-packages. I can do some tests to verify.

Also I think this issue is about reporting a relative path to the package or an absolute path of the installation location of the package. I've checked the related code in nbval but seen nothing outstanding, I need to check the code in pytest to see if there's anything different when dealing with paths.

**Comment by utensil** [comment]
`pip install -e .` does the trick, thanks!

Still I don't know why `pip install .` will ro should be different.

**Comment by vidartf** [comment]
`pip install .` copies the source to the python packages directory. `-e .` leaves the source in place, and instead tells python where your code is located (see https://setuptools.readthedocs.io/en/latest/setuptools.html#development-mode for details).

**Comment by vidartf** [comment]
Closing as answered. Feel free to comment if there are anything else, or if you feel it should be reopened for some reason.
