### ISSUE TITLE
How to run unittest

### ISSUE THREAD

**Issue by eLvErDe** [computationalmodelling/nbval#105]
Hello,

When I run pytest I get

`
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --nbval --current-env
  inifile: None
  rootdir: /home/acecile/packaging/onnx/nbval/nbval-0.9.1
`

I have the feeling that unittest can be run only AFTER the package has been installed system-wide, which looks wrong to me.

Thanks in advance, Adam

**Comment by takluyver** [comment]
nbval has to be installed into whatever environment pytest itself is running in. Pytest's plugin mechanism only works with an installed package.

**Comment by eLvErDe** [comment]
Really? That's a pity. There must be a workaround

**Comment by eLvErDe** [comment]
Actually I'm working on the Debian package which makes things a bit different. Usually tests are being run in the .build folder by importing the module from there, relative.
It is working finr usually but as this module is a pyext extension it makes relative import useless.

**Comment by takluyver** [comment]
It will work for lots of packages, but by no means all of them. E.g. if a package exposes a command-line interface and the tests exercise that, it will need to be set up before the tests work. I'd imagine this will be the same for most pytest plugins and anything else that relies on entry points, such as additional pygments lexers.

**Comment by eLvErDe** [comment]
That's weird because I checked a few existing pytest Debian package and none of them was doing something specific for running tests.
My guess is that they are simply not using themselves in their tests...

**Comment by peeweep** [comment]
I'm facing same issue, my workaround is using `PYTHONPATH=.`,  for example: `PYTHONPATH=. py.test --nbval`
