### ISSUE TITLE
Possible framework alternative

### ISSUE THREAD

**Issue by glass-ships** [computationalmodelling/nbval#120]
Recently, I wrote a python script which uses `nbformat` and `nbconvert` to operate as a simple test that a jupyter notebook runs without error. Output comparison is something I'm interested in but haven't added quite yet. It's available in a gitlab repo [here](https://gitlab.com/glass-ships/analysis-tools/blob/master/nbtest.py).

That said, I'm curious as to why `py.test` is used here preferentially (ie. is there functionality specific to the pytest suite that outweighs the benefit of something like my script? 

Secondary to that, I've noticed in my research that `py.test` has been deprecated in favor of `pytest` - is there any motivation (or need) to update the calls made?

**Comment by takluyver** [comment]
It was just how the project started. pytest does bring some nice architecture for selecting and excluding files, though it probably wouldn't be hard to implement something similar. It's also increasingly what all our projects use to run their regular test suite, so we've generally got it installed anyway.

`py.test` vs `pytest` shouldn't make much difference. Maybe some tests and docs need to be updated.

**Comment by glass-ships** [comment]
Thanks so much for the response! I'll mark this closed and consider both viable options.
