### ISSUE TITLE
nbval not working with parallel/distributed pytest

### ISSUE THREAD

**Issue by CeaVi** [computationalmodelling/nbval#121]
Parallel/distributed testing with pytest (pytest-xdist) fails: it seems that all cells are executed in parallel instead of sequentially, which will obviously not work for most notebooks.

To reproduce, create a notebook doing dependent things in different cells, for example import a package in the first cell and then use it in other packages. Install pytest-xdist. Then, try for example:

```shell
purest -n auto --nbval <notebook file>
```

(the `-n auto` option asking pytest to use all available CPU cores on the machine)

**Comment by vidartf** [comment]
Did you try using the flag recommended in the readme? https://github.com/computationalmodelling/nbval#parallel-execution

**Comment by CeaVi** [comment]
No, thanks, this is indeed solving the problem! (I wonder if nbval would be able to determine automatically whether it is running in a distributed/parallel context?)

**Comment by vidartf** [comment]
I think nbval might be able to detect this. It might make sense for nbval to give a warning if it is in distributed mode, but without loadscope.
