### ISSUE TITLE
Databricks support for code-coverage

### ISSUE THREAD

**Issue by tintinmj** [computationalmodelling/nbval#124]
Though the `nbval` is used for Jupyter notebook, I am not able to implement it in Databricks as it doesn't have `.ipynb` extension. Can a feature be introduced to test Databricks notebook too.

Community version of Databricks can be used for development - https://community.cloud.databricks.com

**Comment by vidartf** [comment]
I think it will work if you add a config file or plugin with:

```python
from nbval import IPyNbFile

def pytest_collect_file(path, parent):
    """
    Collect custom files for use with nbval
    """
    opt = parent.config.option
    if (opt.nbval or opt.nbval_lax) and path.fnmatch("*.ipynb"):  # Change this logic to match your files
        return IPyNbFile(path, parent)
```

**Comment by tintinmj** [comment]
Thanks @vidartf for taking a look into this. I am getting an error when I am trying to compile the code (The error is below). Although Databricks notebooks are not exactly stored as "ipynb", I am not sure how it is stored. I am not able to find anything in their documentation also.

```
ImportError: cannot import name 'IPyNbFile'
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<command-2490636014948600> in <module>
----> 1 from nbval import IPyNbFile
      2 
      3 def pytest_collect_file(path, parent):
      4     """
      5     Collect custom files for use with nbval

ImportError: cannot import name 'IPyNbFile'
```

**Comment by tintinmj** [comment]
Sorry wrongly closed.

**Comment by vidartf** [comment]
Ah, it should import it from `nbval.plugin`.

**Comment by tintinmj** [comment]
@vidartf Yes, now the code compiles but I am not able to understand how to use that for Databricks. As I said, I don't know the extension of Databricks notebook.

**Comment by vidartf** [comment]
I have no idea what databricks are, so I cannot really help with that. That if clause needs to somehow identify databrick files, whatever they are :)

**Comment by tintinmj** [comment]
@vidartf Databricks is *almost* similar to Jupyter Notebook whose backbone is Spark. You can give it a try with free version - https://community.cloud.databricks.com

**Comment by takluyver** [comment]
Is Databricks actually using Jupyter infrastructure? If it's something that looks similar but has a different file format and a different way of executing code, this plugin isn't going to work.

**Comment by tintinmj** [comment]
@takluyver I don't have answer to your first question. But it definitely doesn't store file as '.ipynb'

**Comment by takluyver** [comment]
If you look inside the file with a text editor, is it stored in a JSON structure like Jupyter notebooks, or something else?

**Comment by tintinmj** [comment]
The file is stored in cloud, I don't have access to directly see how this is saved. But if I download the workspace with Workspace-CLI the files get downloaded as `.py` for Python Notebook.

**Comment by takluyver** [comment]
What file were you trying to run nbval with? It won't work with a `.py` file.

**Comment by tintinmj** [comment]
I want to find a way to test and get code coverage for Databricks notebook. Now I don't know what type of file it actually stores over cloud.

**Comment by vidartf** [comment]
Closing due to lack of information about what databrick notebooks are. If more information is shared, we can reopen :)
