### ISSUE TITLE
Ensure notebooks running without error

### ISSUE THREAD

**Issue by wingedRuslan** [computationalmodelling/nbval#125]
Although **nbval** extension is mainly used to compare the existed cell output with the output while testing(running) notebook, I would like to use **nbval** just to make sure that notebooks are running without errors. 

How can I achieve this goal to ensure that running cells **will not** cause any errors?

*My outputs are produced figures*

This will cause all cells to fail because the output information contains the memory address where the figure is stored (obviously, this is the unique value so it can't be compared).
```
py.test --nbval visualisations_tutorial.ipynb
```

My workaround(?) solution is to place this comment in a cell so that the output is not compared.
```
# NBVAL_IGNORE_OUTPUT
py.test --nbval visualisations_tutorial.ipynb
```

Is there a better solution to ensure that the notebooks are running without errors?

If you have any questions, feel free to ask.

**Comment by takluyver** [comment]
Use `--nbval-lax`. You can also use this as a starting point and then tag specific cells for output checking.

(With hindsight, I wish `--nbval` did this by default, and you could use some extra flag to check all output. But it's tricky to change that now.)

**Comment by wingedRuslan** [comment]
@takluyver gotcha, thanks! 

By the way, while searching for tools/ideas on how to ensure notebooks are running without errors, I've encountered this test:

<details><summary> Alternative test </summary>

```
import subprocess
import tempfile


def _exec_notebook(path):
    with tempfile.NamedTemporaryFile(suffix=".ipynb") as fout:
        args = ["jupyter", "nbconvert", "--to", "notebook", "--execute",
                "--ExecutePreprocessor.timeout=1000",
                "--output", fout.name, path]
        subprocess.check_call(args)


def test():
    _exec_notebook('visualisations_tutorial.ipynb')
```
</details>

Could you please shortly answer which option is more "reliable"? or both solutions are equally good?

**Comment by takluyver** [comment]
I'd say they're probably about equally reliable.

Nbval is better integrated with pytest, so you might get clearer errors if it fails, and you get a test dot for each cell rather than it hanging until the whole notebook is run. It might also be slightly faster, because it only starts one extra process (the kernel), whereas the custom approach starts two (nbconvert and the kernel).

The custom approach is more explicit - there's less going on that you can't see.

**Comment by wingedRuslan** [comment]
@takluyver, thanks a lot! Closing issue
