### ISSUE TITLE
RuntimeError with py38 on Windows

### ISSUE THREAD

**Issue by s-weigand** [computationalmodelling/nbval#128]
I'm not sure if I'm barking up the wrong tree and this is a problem with `jupyter_client`, but I'm sure you are more qualified to assess that.

__Description:__
Python version: 3.8
Os: Windows 10 (`windows-latest` on github actions)

If you [run nbval with this settings](https://github.com/s-weigand/python-tools-for-students/runs/334654218#step:5:346), The kernel does not respond and throws:

`RuntimeError: Kernel didn't respond in 60 seconds`

This problem only occurs on Windows, MacOx and Linux work fine.

PS: If you are interested to migrate you tests to github actions as well, I could make a PR for that.

**Comment by takluyver** [comment]
I suspect this was actually an issue with ipykernel: https://github.com/ipython/ipykernel/pull/456

> PS: If you are interested to migrate you tests to github actions as well, I could make a PR for that.

I haven't got round to looking into them. Is there any particular advantage if there's a CI setup that already works?

**Comment by s-weigand** [comment]
Thanks for the info, I will wait for a new release of ipykernel and try again ^^

As for GH actions:
- The worker have [better hardware specs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources) compared to other free CI services
- You can tests Windows, Linux and MacOs [in one palce](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#example-including-configurations-in-a-matrix-build)
- And you can run up to 20 concurrent jobs (5 concurrent MacOs jobs)

**Comment by vidartf** [comment]
Closing as solved upstream. If that's not the case, please comment, and I'll reopen :)
