### ISSUE TITLE
Please allow adapting startup_timeout

### ISSUE THREAD

**Issue by jensseidel** [computationalmodelling/nbval#133]
Hi,

from time to time I get an error using nbval because the default startup_timeout of 60 s is too low. Can you please make this timeout accessible similar to the option --nbval-cell-timeout?

lib/python3.5/site-packages/nbval/kernel.py:88:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

startup_timeout = 60, kernel_name = ':nbval-parent-env'
kwargs = {'cwd': '/build/', 'stderr': <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>}
km = <jupyter_client.manager.KernelManager object at 0x7fd4d16af6a0>
kc = <jupyter_client.blocking.client.BlockingKernelClient object at 0x7fd4d16af470>

    def start_new_kernel(startup_timeout=60, kernel_name='python', **kwargs):
        """Start a new kernel, and return its Manager and Client"""
        logger.debug('Starting new kernel: "%s"' % kernel_name)
        km = KernelManager(kernel_name=kernel_name,
                           kernel_spec_manager=NbvalKernelspecManager())
        km.start_kernel(**kwargs)
        kc = km.client()
        kc.start_channels()
        try:
>           kc.wait_for_ready(timeout=startup_timeout)
...
RuntimeError: Kernel didn't respond in 60 seconds

**Comment by vidartf** [comment]
This seems reasonable to make configurable, same as with https://github.com/computationalmodelling/nbval/issues/136 . PRs welcome :)
