### ISSUE TITLE
Allow user to specify kernel

### ISSUE THREAD

**Issue by ceball** [computationalmodelling/nbval#140]
nbval defaults to starting the kernel named in the notebook. Alternatively, `--current-env` can be supplied to start the kernel in the same environment as the test process. If I have a notebook with no stored kernel info (e.g. because that info is deliberately not stored in git), and I want to run the notebook in a particular environment (which might well not contain pytest), there doesn't seem to be a way for me to do it.

Assuming the above is correct, I'd like to add an option to allow the user to specify the kernel to use. What do you think?

I.e. something like nbconvert has:

> The second traitlet, kernel_name, allows specifying the name of the kernel to be used for the execution. By default, the kernel name is obtained from the notebook metadata. The traitlet kernel_name allows specifying a user-defined kernel, overriding the value in the notebook metadata. A common use case is that of a Python 2/3 library which includes documentation/testing notebooks. These notebooks will specify either a python2 or python3 kernel in their metadata (depending on the kernel used the last time the notebook was saved). In reality, these notebooks will work on both Python 2 and Python 3, and, for testing, it is important to be able to execute them programmatically on both versions. Here the traitlet kernel_name helps simplify and maintain consistency: we can just run a notebook twice, specifying first “python2” and then “python3” as the kernel name.

(https://nbconvert.readthedocs.io/en/latest/execute_api.html)

**Comment by vidartf** [comment]
Adding an argument to specify the kernel name seems reasonable to me. I would probably have it fall over if both that and `--current-env` was used. Do you want to do a PR implementing this?
