### ISSUE TITLE
Rename #PYTEST_VALIDATE_IGNORE_OUTPUT

### ISSUE THREAD

**Issue by fangohr** [computationalmodelling/nbval#16]
The keyword `#PYTEST_VALIDATE_IGNORE_OUTPUT` used to ignore comparison of computed and saved output originates from a time when the tool was called 'pytest-validate'. As the name now is 'nbval' (standing for NoteBook VALidation), it seems sensible to rename that keyword to `#NBVAL_IGNORE_OUTPUT`.

We should still allow #PYTEST_VALIDATE_IGNORE_OUTPUT to be used for backwards compatibility.

Must update documentation accordingly.

**Comment by fangohr** [comment]
See also #17 for explanation of the long name (`*_IGNORE_OUTPUT).

**Comment by takluyver** [comment]
Fixed by #19.
