### ISSUE TITLE
drop support for Python 2.7/3.5

### ISSUE THREAD

**Issue by gliptak** [computationalmodelling/nbval#160]
Would you be open to PRs for above?

https://devguide.python.org/#status-of-python-branches

**Comment by takluyver** [comment]
I'd be fine with that, but it's mainly up to @vidartf, as he does most of the maintenance.

**Comment by vidartf** [comment]
I won't mind either, as it should be a pretty small change to review.

**Comment by eric-wieser** [comment]
This can be closed thanks to #162, right?
