### ISSUE TITLE
Should we allow non-execution of cells for nbval?

### ISSUE THREAD

**Issue by fangohr** [computationalmodelling/nbval#17]
We have a keyword `#NBVAL_IGNORE_OUTPUT` (see issue #16) that stops nbval from comparing the computed output against the stored output for the input cell in which the string `#NBVAL_IGNORE_OUTPUT` is found. However, the input cell code is still executed. This is normally useful as later cells may depend on it.

Would it be useful to also support another feature, maybe using the keyword `#NBVAL_IGNORE`, which means that the input cell in which this is found will not be executed at all? This could be used in cases where we know that the execution causes side effects on the host that executes the command, which we may not want or need as part of the nbval testing.

**Comment by ryanpepper** [comment]
I think this should be very straightforward to implement in the current framework.

**Comment by vidartf** [comment]
I like this, but would maybe this to use the word "skip" in the name, as that is consistent with the py.test terminology.
