### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by tschm** [computationalmodelling/nbval#173]
Hello, 

version 0.9.6 of your neat tool does not include the work on specifying kernel names etc.
I wonder whether you could release the current state of your tool on pypi.

Many thanks

Thomas

**Comment by kanderso-nrel** [comment]
I think this can be closed now that 0.10.0 is released on PyPI: https://pypi.org/project/nbval/#history

**Comment by takluyver** [comment]
Thanks!
