### ISSUE TITLE
Option to only check output on marked cells

### ISSUE THREAD

**Issue by takluyver** [computationalmodelling/nbval#18]
We currently check output on all cells not explicitly marked with the `IGNORE_OUTPUT` comment.

Because many outputs can be variable, I'd like an alternative way to use nbval which runs the whole notebook, but only compares the output of cells marked with something like `# NBVAL_CHECK_OUTPUT`.

**Comment by fangohr** [comment]
Sounds good to me. 

We should list all the keywords together and make sure they display a systematic naming pattern relating to their functionality, maybe before addressing #4 and #17 and #16.
