### ISSUE TITLE
Should not assume that matplotlib is available

### ISSUE THREAD

**Issue by takluyver** [computationalmodelling/nbval#20]
We currently pass `--matplotlib=inline` when starting the kernel, to force figures to appear inline. However, this means that if `matplotlib` is not installed in the environment where the kernel runs (which may not be the same as the one nbval is running in), the kernel will fail to start.

From comments on #6.

**Comment by minrk** [comment]
With recent versions of ipykernel / matplotlib, `--matplotlib=inline` shouldn't be necessary anymore.
