### ISSUE TITLE
Sanitize replace regex

### ISSUE THREAD

**Issue by mloubout** [computationalmodelling/nbval#206]
Is there a way to make the `--nbval-sanitize-with` to use regex for the replacement as well, i.e something like

```
[regex1]
regex: \w+\(\d+\)
replace: d
```

currently I can only make it hard-code "d" which will obviously fail too.

**Comment by takluyver** [comment]
The replacement uses [`re.sub()`](https://docs.python.org/3/library/re.html#re.sub), so references like `\1` should work.

> currently I can only make it hard-code "d" which will obviously fail too.

Will it? The usual purpose for this sanitise mechanism is to replace things like timestamps with a fixed string such as `TIMESTAMP`.

**Comment by mloubout** [comment]
I found a better way to fix my issue so it's fine, sorry for that.
