### ISSUE TITLE
Smarter picking of kernel to start

### ISSUE THREAD

**Issue by takluyver** [computationalmodelling/nbval#21]
Currently, nbval always starts the default Python kernel, though this is not necessarily running in the same Python environment as nbval itself (see discussion on #6).

1. In the default case, we should probably pick the kernel to start based on notebook metadata, like nbconvert does for `--execute`. This would allow validating notebooks in other languages.
2. We may also want an option which forces it to start a Python kernel in the same Python environment as nbconvert itself, so we know that test dependencies affect what's available in the kernel. Thoughts on what this should be called?

**Comment by minrk** [comment]
From my perspective, 'parent' environment is how I would refer to it, since nbval is the parent of the kernel. That might require too much understanding of the architecture to be clear, though. From a user's perspective, perhaps 'current environment' is more intuitive?
