### ISSUE TITLE
I wonder when a Python 3.13 compatible release is planned?

### ISSUE THREAD

**Issue by andife** [computationalmodelling/nbval#212]
Hi?
I wonder when a Python 3.13 compatible release is planned?

What needs to be done beforehand?

Andreas

**Comment by takluyver** [comment]
Have you tried the current release with python 3.13? You set up the tests
on 3.13 with no problem, so it may be that it just works already.

If not, I'll do a release soon.

**Comment by andife** [comment]
Thanks,
No you are right it works under 3.13, maybe it was related to ipython or jupyter or a combination. In any case it works now

**Comment by takluyver** [comment]
Great, thanks for testing!
