### ISSUE TITLE
Check links (URLs) in notebook

### ISSUE THREAD

**Issue by fangohr** [computationalmodelling/nbval#28]
A possible extension of the notebook testing: can we check URLs (in the markdown presumably) to see if those are accessible (i.e. URL linting)? 

This could be activated by an additional switch (maybe `--url-lint` or so) and report failures if a URL is not accessible. (To run the test, Internet access will be required.)

This was proposed at the Jupyter Workshop January 2017 in Edinburgh (http://opendreamkit.org/meetings/2017-01-16-ICMS/programme/).

**Comment by takluyver** [comment]
This could also be an entirely separate py.test plugin - a general link checker which knows how to handle ipynb files among others.

**Comment by vidartf** [comment]
A plugin checking links in markdown files would have potentially very wide use.

**Comment by minrk** [comment]
Following the example of sphinx's [make linkcheck](http://www.sphinx-doc.org/en/stable/_modules/sphinx/builders/linkcheck.html?highlight=linkcheck) might provide insight. Checking the links in markdown shouldn't be too difficult.

@takluyver do you think this would be better as a separate package, or part of nbval?

**Comment by takluyver** [comment]
I'd be inclined to do it as a separate package.

**Comment by minrk** [comment]
OK. I've got it working in nbval [here](https://github.com/minrk/nbval/tree/check-links), but a separate package makes sense, too.

**Comment by minrk** [comment]
I just pushed what I was doing as [pytest-check-links](https://github.com/minrk/pytest-check-links), so that you should now be able to do:

    pytest --check-links /path/to/notebook.ipynb

**Comment by takluyver** [comment]
Closing here - please file further issues relating to this on the repo Min linked above.
