### ISSUE TITLE
add `ipykernel` to requirements

### ISSUE THREAD

**Issue by fangohr** [computationalmodelling/nbval#31]
It seems we need `ipykernel` as one of the requirements for nbval. 

However, our tests don't show that so far. I suggest we create a docker container as part of the testing process, and try to run `py.test --version` or a quick test on something inside the container to check the requirements.

This is based on finding that the requirement was missing for tests using `--nbval` in joommf/oommfc (https://github.com/joommf/oommfc/commit/613c4777ff4afc2b66bdbb3e2abbbb942475d1ad)

**Comment by takluyver** [comment]
This is hidden on Travis because we're creating a conda env with `jupyter` installed. If we can rely on installing nbval to pull in all its dependencies, we should do that to show up issues like this.

**Comment by fangohr** [comment]
Thanks Thomas.

Close with pull request https://github.com/computationalmodelling/nbval/pull/32
