### ISSUE TITLE
Should nbval be testing all cells?

### ISSUE THREAD

**Issue by russel** [computationalmodelling/nbval#38]
I have some %timeit cells, as well as some code, markdown and pytest cells in a notebook and when running nbval, all the %timeit cells create test fails as the time taken to run the code is different between the nbval execution and the number in the notebook. Is this to be expected?

**Comment by russel** [comment]
It seems I should have been using --nbval-lax. Maybe this is a non-question.

**Comment by takluyver** [comment]
It should test all code cells - that includes cells containing cell magics like `%%timeit`. It doesn't do anything with markdown cells.

Both `--nbval` and `--nbval-lax` will run all code cells, and check that they run without an error. With `--nbval`, it checks the output of all cells that don't have an `# NBVAL_IGNORE_OUTPUT` comment. With `--nbval-lax`, it only checks the output for cells that do have `# NBVAL_CHECK_OUTPUT`.

I'll close this now, but we can keep using the comments if there's anything that's not clear.
