### ISSUE TITLE
Option to ignore error on cell

### ISSUE THREAD

**Issue by owlas** [computationalmodelling/nbval#4]
Its possible to ignore the cell output but not errors. Sometimes we might want a cell failure and not have it tested.

**Comment by par2** [comment]
+1

**Comment by fangohr** [comment]
Ah, would the idea proposed in #17 provide this? #17 says that a whole input cell should not be executed.

**Comment by takluyver** [comment]
It would sort of offer this. There may be some situations where you want to ignore errors, but still execute a cell.

**Comment by vidartf** [comment]
An extension of this would be to specify *expected* cell failure, i.e. fail if the cell does not give an error. Output comparison should then also check that traceback matches.

**Comment by takluyver** [comment]
Makes sense. I think this is all relatively low priority, though, as I think notebooks which deliberately include an uncaught exception are unusual.

Traceback comparison needs to be a bit smart, because by default Python tracebacks include full paths to files,  which is not what we want to check.

**Comment by BjornFJohansson** [comment]
+1 
I have a notebook that demonstrates an expected exception in my package and I have set up travis to run tests of a collection of notebooks using nbval. At least ignore execution of a cell would be practical since travis now reports failure although all is fine.

**Comment by takluyver** [comment]
@wence- has done the work and it's been merged, we just need to make a new release with it in.
