### ISSUE TITLE
Count only code cells for cell numbers?

### ISSUE THREAD

**Issue by takluyver** [computationalmodelling/nbval#49]
nbval currently names tests as e.g. 'Cell 3', counting all the cells of the notebook including markdown cells. Jupyter does not expose any visible numbering of cells, but if you start the kernel and 'run all', you will effectively get a numbering of only code cells. So nbval's 'Cell 3' could have an `In [1]:` prompt by it.

I think it would be better for the names in nbval to look like 'Code cell 1', so it's easy to match up to a notebook that has been executed straight-through.

@vidartf I assume the nbdime reporting doesn't rely on these names?

**Comment by vidartf** [comment]
I agree with this, as the actual comments in the code previously indicated that this should be the case. I did a double take on the nbdime reporter, and couldn't find anything that relies on that. It should only be a matter of checking that nbdime also picks up on the new names once implemented (it should).

**Comment by minrk** [comment]
It could even use the actual execution count from the execute replies, so that skipped cells, etc. don't show up. I'm not sure if that would be better or not. It may depend on the nature of why the cell is skipped.

**Comment by vidartf** [comment]
The skipped code cells should still have a unique ID for pytest (`pytest --nbval -v` would look weird if not), so I would argue they should still be counted.

**Comment by vidartf** [comment]
Fix proposed in #51.
