### ISSUE TITLE
Release 0.5

### ISSUE THREAD

**Issue by takluyver** [computationalmodelling/nbval#52]
We've made quite a few changes since the last release, and we should try to make a new release.

@vidartf @fangohr is there anything high priority which we should fix before releasing 0.5?

**Comment by vidartf** [comment]
Everything seems good to me! 👍

**Comment by fangohr** [comment]
Thanks both. I agree that having a 'final' release for this deliverable is the way to go. I am also happy with the overall state of the tool.

(At some point, I would like to have somebody look at #7 -- this would be very cool if we can make it work. But this goes beyond the scope of the deliverable and thus there is no need to do it now.)

So I support releasing version 0.5, to update the documentation and deliverable report  with this (and maybe also take a Zenodo snapshot so we have a permanent identifier of this version).

I am currently travelling with intermittent Internet access - please finalise this without waiting for further input/confirmation from me.

**Comment by takluyver** [comment]
0.5 is released

**Comment by takluyver** [comment]
I tried to connect it to Zenodo, but it's not visible there; @fangohr it looks like you need to [enable application access for the CMG organisation](https://help.github.com/articles/approving-third-party-applications-for-your-organization/)
