### ISSUE TITLE
Unable to sanitize output_type

### ISSUE THREAD

**Issue by rmjarvis** [computationalmodelling/nbval#60]
I'm getting a discrepancy in my output_types with nbval 0.5 that doesn't show up in nbval 0.4:
```
______________________________________________ cell 4 ______________________________________________
Notebook cell execution failed
Cell 4: Cell outputs differ

Input:
treecorr.corr2(config)

Traceback: mismatch 'output_type'
<<<<<<<<<<<< Reference output from ipynb file:
stream
============ disagrees with newly computed (test) output:  
streamst...<snip base64, md5=1d90ad9225fdb1ef...>
>>>>>>>>>>>>
```
The output is from a logger object with `logging.StreamHandler(stream=sys.stdout)` for its handler.  My Jupiter installation (4.1.0) and nbval 0.4.0 both give the output_type as simply `stream`.  But nbval 0.5 has the above weird `streamst` thing.

Anyway, I thought I'd be able to ignore this using my sanitize file.  I added
```
[output_type]
regex: stream.*
replace: stream
```
but it didn't work.  It turns out that you [don't run](https://github.com/computationalmodelling/nbval/blob/093d38d4853f3b3cf7c23eeac5ab45d7f56ea8bf/nbval/plugin.py#L724) sanitize on the `output_type` field.

So what is my workaround to deal with this?  Thanks for any help you can provide.

**Comment by vidartf** [comment]
This looks like a duplicate of #54. Please check whether PR #57 fixes this for you.

**Comment by vidartf** [comment]
FYI: This PR should be installable via `pip install https://github.com/vidartf/nbval/archive/coalesce-outputs.zip`.

**Comment by rmjarvis** [comment]
Yes.  That does fix things.  Thanks!
