### ISSUE TITLE
Record nbval test coverage in coverage 

### ISSUE THREAD

**Issue by fangohr** [computationalmodelling/nbval#7]
A description of the issue is provided in this jupyter notebook [issues/7/issue.ipynb](../blob/master/issues/7/issue.ipynb).

**Comment by owlas** [comment]
This is a really interesting feature Hans. What would 'coverage' mean in the context of notebook regression testing?

**Comment by fangohr** [comment]
The rough answer is that output cell [4] in https://github.com/computationalmodelling/nbval/blob/master/issues/7/issue.ipynb should report
<pre>
Name    Stmts   Miss  Cover
---------------------------
lib         4      0   100%
</pre>
instead of the current output that is
<pre>
Name    Stmts   Miss  Cover
---------------------------
lib         4      1    75%
</pre>

The argument for this is that when we run nbval on https://github.com/computationalmodelling/nbval/blob/master/issues/7/tutorial_lib.ipynb, we effectively have tests that execute all the code in https://github.com/computationalmodelling/nbval/blob/master/issues/7/lib.py


You may have thought further already, and there are some design questions to be asked and answered. For example, we could call the code in `lib.py` from the notebook, but we may not inspect the return value at all in the notebook. For example:
<pre>
a = lib.myprod(1, 2)
</pre>
Running this inside a notebook through nbval testing would be a much weaker test than is in the demonstration at https://github.com/computationalmodelling/nbval/blob/master/issues/7/tutorial_lib.ipynb where we actually check that `a` has the right value. 

If the statement above (`a = lib.myprod(1,2)`) is tested via nbval and passes, it would basically confirm that `myprod()` exists in `lib` as a callable object, takes two arguments, and doesn't raise exceptions.

Should this 'weaker test' count as being 'covered by a test'? That's the question. For our use case, I would say: 'yes': Having this minimal cover in place is a lot better than None. It also avoids the question how weak or strong a test needs to be to contributing to the coverage. But others may disagree. 

As a first approximation, I would propose that all the code that is executed through the commands in the input cells of the notebook should count as the coverage of that notebook.

I haven't thought long about this though - other ideas and thoughts would be useful.

**Comment by nedbat** [comment]
I got a coverage.py issue written about this: https://bitbucket.org/ned/coveragepy/issues/569/measure-coverage-of-jupyter-notebook  , at least I think it's the same issue.  Let me know if I can help.

**Comment by vidartf** [comment]
A PR fixing this is open in #53 .

**Comment by vidartf** [comment]
In terms of help, trying it out and letting us know if this works for you or not would be appreciated 👍
