### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by fangohr** [computationalmodelling/nbval#78]
We need an overview of what NBVAL can do, including a screen shoot of typical test output to explain quickly why people may (or may not) want to read further about the tool. This might be an opportunity to move documentation to read the docs, to generally be more in line with what is expected from potential customers.

**Comment by vidartf** [comment]
See #72 for a attempted start on this.

**Comment by vidartf** [comment]
We're now on RTD (http://nbval.readthedocs.io). The docs could still get some refurbishment as outlined in the issue description though. A screenshot might not be needed, if we are able to get the output into the notebook (`!py.test --nbval ...`?).

**Comment by jgefele** [comment]
Hi and thanks for this great project!

Some additions from a (new) user's perspective:
 * `--nbdime` should be documented. It's so super useful.
 * in the section about figures I read `Currently, only the matplotlib text output of the Figure is compared, but it is possible to modify the plugin to allow comparison of the image whole string.`. It would be nice to know how :-) Currently I help myself with this hack:
```
def plt_show():
    """The visual effect is more or less the same as plt.show().
       However, this way the 'nbval' notebook tester can check the plots."""
    import io
    file_obj = io.BytesIO()
    plt.savefig(file_obj, format='png')
    plt.close()
    display({'image/png':file_obj.getvalue()}, raw=True)
plt.show = plt_show
```

**Comment by takluyver** [comment]
Thanks, we should definitely document the `--nbdime` option.

The bit about matplotlib figures is a bit out of date - they are compared now if you're using it with nbdime. If you're using `%matplotlib inline` in your notebook, you shouldn't need any extra code to make it work.

**Comment by jgefele** [comment]
It's still useful in case of a continuous integration server, though. Here I have no option to use an interactive diff. Or is a mode of operation for `--nbdime` that works on text mode server?

**Comment by takluyver** [comment]
If your use it without `--nbdime`, I don't think your hack will actually make it compare the output - it ignores the `image/png` mimetype unless nbdime is in use.

nbdime can output to a terminal. I don't know if you can configure it to do that in nbval. @vidartf ?

**Comment by vidartf** [comment]
You cannot currently configure it, but I'm also unsure if that would be a good long term plan. It is probably better to add an option to nbval to allow `image/png` to be compared. The output diff printer will detect that it is a base64 string and snip it, similarly to how nbdime does it.

E.g. add a flag `compare-images`, which if true will compare the image data strings, but still output to the terminal.

**Comment by vidartf** [comment]
That being said, if you follow the example of the last cell in the documentation, you can add the following code to be executed (in the notebook, or possibly in conf.py file).

```python
def pytest_collectstart(collector):
    collector.skip_compare.remove('image/png')
```

**Comment by vidartf** [comment]
Closing, as open-ended issues like this will never be closed. Feel free to open other issues/PRs about specific, actionable points about the documentation though!
