### ISSUE TITLE
How to determine if a Notebook has cell errors

### ISSUE THREAD

**Issue by rrussell39** [computationalmodelling/nbval#79]
I am writing a New Relic Synthetic (Javascript) which opens and runs a Notebook. I block until Jupyter.notebook.kernel_busy is false. Now I need to know if the notebook completed successfully with NO errors in any cells. Is there such a boolean or status or event or ??? I can monitor to determine success?
Basically I need a programmatic way to know if a Notebook has completed with errors or success.

**Comment by takluyver** [comment]
It sounds like you're running a notebook in the web interface, so I'll close this in favour of jupyter/notebook#3098. Nbval is a Python tool to run notebooks non-interactively and check for errors: it doesn't run in the browser.
