### ISSUE TITLE
Failing on a cell that returns no output normally

### ISSUE THREAD

**Issue by psychemedia** [computationalmodelling/nbval#81]
I have a notebook in which a code cell is used to run a shell command that, if all goes well, does not return anything. If the shell command breaks, an error message is returned and displayed as code cell output.

This error does not seem to result in a failed test.

To test this, I created a notebook with 3 code cells, `print('test')` in each, ran the notebook, cleared the output of the second code cell and then ran a test. It passed whereas I would have expected it to fail in the sense of cell 2 generating an output where there was none originally.

**Comment by takluyver** [comment]
Thanks - #82 should fix it.

**Comment by takluyver** [comment]
Released nbval 0.8.
