### ISSUE TITLE
Missing coverage dependency

### ISSUE THREAD

**Issue by serge-sans-paille** [computationalmodelling/nbval#84]
`nbval` now depends from the `coverage` package, as required in `nbval/cover.py`

**Comment by serge-sans-paille** [comment]
See https://travis-ci.org/serge-sans-paille/pythran/jobs/328943992 for a backtrace :-)

**Comment by takluyver** [comment]
Thanks! Want to do a PR?

**Comment by serge-sans-paille** [comment]
why not, preparing that.

**Comment by serge-sans-paille** [comment]
See #85

**Comment by takluyver** [comment]
Fixed by #85.
