### ISSUE TITLE
Option to ignore logs (output to stderr)

### ISSUE THREAD

**Issue by gartentrio** [computationalmodelling/nbval#88]
Hi,
it would be great if there was an option to ignore output to stderr altogether when running tests. Have you considered implementing this?
Thanks
Mark

**Comment by vidartf** [comment]
Would you mind giving an example, just to be clear what kind of log/stderr output we are talking about? There are many potential sources of such output, and I want to avoid us talking past each other.

**Comment by vidartf** [comment]
Thanks for clearing that up. This should be possible currently by following [this part](https://nbval.readthedocs.io/en/latest/#Skipping-certain-output-types) of the documentation. Adjusted for what you are doing:

```python
def pytest_collectstart(collector):
    if collector.fspath and collector.fspath.ext == '.ipynb':
        collector.skip_compare += ('stderr',)
```

As you can see, you can inspect the `fspath` property to only apply this to certain files. Currently, it is not possible to configure this per cell, but that should be possible with minor changes to nbval.

**Comment by gartentrio** [comment]
Works like a charm, thank you.
