### ISSUE TITLE
run loops for just one iteration?

### ISSUE THREAD

**Issue by jeff-regier** [computationalmodelling/nbval#96]
Is there a way to have nbval-lax run slightly different code than Jupyter would? In the Jupyter notebook, I have an algorithm that runs for a long time -- too long for unit tests. I'd like to nbval-lax to run that loop for just 1 iteration. Is there a way to do that?

**Comment by takluyver** [comment]
You could run one iteration as an example, and then have the full looping in a cell that nbval skips over: https://nbval.readthedocs.io/en/latest/#Skipping-specific-cells

**Comment by jeff-regier** [comment]
Ah, OK. That's better that not having the notebooks tested at all.

I was also thinking I could perhaps have the unit tests modify the file before running it, e.g. by running `sed` with regex to change the code slightly, but I'm not entirely happy with that solution.

Thanks for the response!

**Comment by takluyver** [comment]
Another option for testing the code in notebooks would be to use [nbformat](http://nbformat.readthedocs.io/en/latest/) to extract it and do whatever you like with it. E.g. you could identify function definitions from the AST and test those. That may be more complex and error prone, though - nbval is a convenient solution for very simple 'does this still run' testing.
