### ISSUE TITLE
pytest --nbval comparing inline images from extension

### ISSUE THREAD

**Issue by stuaxo** [computationalmodelling/nbval#97]
Hi,
   I'm trying to use pytest --nbval to test output from cairo-jupyter.

We use display(surface), which outputs png data into the notebook.

When I try and run inside pytest --nbval, it acts as though the extension is not loaded, although the cell before it has ```%reload_ext cairo_jupyter```.

Any idea whats going on ?

extension (info here on how to install)
https://github.com/fomightez/cairo-jupyter

notebook - you can see the output here, if you view in raw mode you can see the cell output is a data url with a png
https://github.com/fomightez/cairo-jupyter/blob/master/demos/cairo_jupyter_extension.ipynb

output
```
$ py.test --nbval demos/cairo_jupyter_extension.ipynb 
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.6.5, pytest-3.7.1, py-1.5.4, pluggy-0.7.1
rootdir: /home/stu/projects/mine/cairo-jupyter, inifile:
plugins: nbval-0.9.1
collected 3 items                                                                                                                                                                             

demos/cairo_jupyter_extension.ipynb .F.                                                                                                                                                 [100%]

========================================================================================== FAILURES ===========================================================================================
_________________________________________________________________________ demos/cairo_jupyter_extension.ipynb::Cell 1 _________________________________________________________________________
Notebook cell execution failed
Cell 1: Cell outputs differ

Input:
%load_ext cairo_jupyter

# Using display with cairo surfaces
import cairocffi as cairo

surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, 300, 300)
    
cr = cairo.Context(surface)

for i in range(16):
    cr.save()
    cr.translate(150, 150)
    cr.set_source_rgba(0.7, 0.9, 0.0, 0.25)
    cr.rotate(i * 0.1)
    cr.rectangle(-50, -50, 100, 100)
    cr.stroke()
    cr.restore()

display(surface)

Traceback:
 mismatch 'text/plain'

 assert reference_output == test_output failed:

  '<cairocffi.s...7eff8065dc88>' == '<cairocffi.su...7f3ec81aaa90>'
  - <cairocffi.surfaces.ImageSurface at 0x7eff8065dc88>
  ?                                         -------  ^
  + <cairocffi.surfaces.ImageSurface at 0x7f3ec81aaa90>
  ?                                        ++   ^^^^^^


============================================================================= 1 failed, 2 passed in 2.13 seconds ==============================================================================
```

**Comment by vidartf** [comment]
The output that you have included does not say anything about the PNG output. The only thing it is complaining about is the `text/plain` output data (repr of `cairocffi.surfaces.ImageSurface`), which contains a ~random memory address. I would either add a sanitizer for that repr, or add a deterministic `__repr__()` method to the cairo class.

Is there another reason to conclude that the extension is not loaded?

**Comment by stuaxo** [comment]
My extension provides a ipython formatter, that outputs it as a png, the notebook can handle this.

If you have an instance (say a cairocffi.surfaces.ImageSurface), you can ask jupyter is it has a formatter and use that to grab the content of the cell and output to a file, like example below.

It works with my extension, and should work with anything that jupyter can render using pngs...  no idea if it's 'correct' as I built it through exploration just now.

There are handlers for other mimetypes, so if you can handle those you could implement them too, but I don't know how you'd prioritise them if more than one was found for instance.

```python
from base64 import b64decode
from IPython.core import display

def get_png_formatter(instance):
    formatters = get_ipython().display_formatter.formatters['image/png']
    try:
        return formatters.lookup(instance)
    except KeyError:
        return None

formatter = get_png_formatter(crr)
if formatter is not None:
    data = formatter(crr)
    with open('/tmp/blah.png', 'w') as f:
        f.write(data)
```

**Comment by vidartf** [comment]
Oh, then it is maybe more relevant that nbval does not compare images (jpeg/png) by default (https://github.com/computationalmodelling/nbval/blob/170ed02b7236f5de3764134aa16576d3f75ae602/nbval/plugin.py#L217). To test this, install `nbdime` and add the `--nbdime` flag to the pytest command. Then it should compare the images as well, and present the test report in a browser window. Maybe this is not what you ultimately want, but then we can at least narrow the problem a little.

**Comment by vidartf** [comment]
PS: For completeness, it would be nice if you could restate the problem in terms of expected behavior vs. actual behavior. E.g. "when I do A, I expect B to happen. Instead C happens".

**Comment by stuaxo** [comment]
Sorry, it was quite a long time since I tried nbval and I had forgotten a bit what it did.

Problem:

I expected to be able to use nbval to verify a cell that generates an inline image exactly matching a precious run.

Since an exact match is wanted, checking the data returned is good as a first cut.

Extra info -the image was generated using the Jupyter Cairo extension, but this shouldn't make a difference.

**Comment by stuaxo** [comment]
OK, I know enough to be concise now -

When I create a notebook containing embedded PNG images I expect nbval to be able to compare the PNG data, instead it outputs an error ```mismatch 'text/plain'```.

Notebook demonstrating the issue.
https://gist.github.com/stuaxo/ef022dcb73c12077b14171d1bc1b5589

This also affects extensions that use embeded pngs to output to cells such as cairo-jupyter.


Log using the notebook above:

```
===================================== test session starts =====================================
platform linux -- Python 3.6.5, pytest-3.8.2, py-1.6.0, pluggy-0.7.1
rootdir: /home/stu/projects/mine/scratch/notebooks, inifile:
plugins: nbval-0.9.1
collected 1 item                                                                              

Notebook with PNG.ipynb F                                                               [100%]

========================================== FAILURES ===========================================
_______________________________ Notebook with PNG.ipynb::Cell 0 _______________________________
Notebook cell execution failed
Cell 0: Cell outputs differ

Input:
import io

from IPython.display import display
from PIL import Image


path="Raspi_Colour_R.png"
        
with open(path, 'rb') as f:
    inline_image = Image.open(io.BytesIO(f.read()))
    display(inline_image)

Traceback:
 mismatch 'text/plain'

 assert reference_output == test_output failed:

  '<PIL.PngImag...7FFB2C071EF0>' == '<PIL.PngImage...7FAE093AF860>'
  Skipping 61 identical leading characters in diff, use -v to show
  - 67 at 0x7FFB2C071EF0>
  + 67 at 0x7FAE093AF860>


====================================== warnings summary =======================================
/home/stu/.virtualenvs/scratch/local/lib/python3.6/site-packages/jupyter_client/manager.py:62: DeprecationWarning: KernelManager._kernel_spec_manager_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
  def _kernel_spec_manager_changed(self):

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================ 1 failed, 1 warnings in 2.12 seconds ============================
```

**Comment by vidartf** [comment]
As mentioned in https://github.com/computationalmodelling/nbval/issues/78, this part could be documented better, but you should be able to enable image comparison by adding a conf.py file to the directory of your notebooks with the following entry:

```python
def pytest_collectstart(collector):
    collector.skip_compare.remove('image/png')
```

**Comment by stuaxo** [comment]
I'll have a look at that.

Is this a setting that can be added in a pytest.ini ?

I'd be interested in adding a more informative error message, any idea where the error is thrown?

**Comment by vidartf** [comment]
There are two issues for you:
- `img/png` is not being compared. You should be able to enable that as outlined above.
- `text/plain` is being compared, and the text/plain of your objects include a random memory address. To avoid this, you should add a sanitation filter. See the documentation for details: https://nbval.readthedocs.io/en/latest/#REGEX-Output-sanitizing

**Comment by vidartf** [comment]
> Is this a setting that can be added in a pytest.ini ?

Not currently no, but it might be relevant to add this as a CLI/config option.

**Comment by stuaxo** [comment]
Ahh.. right, I thought this

```
Traceback:
 mismatch 'text/plain'

 assert reference_output == test_output failed:
```

Was an actual traceback from nbval because I'd caused an exception somewhere.

> img/png is not being compared. You should be able to enable that as outlined above.
> [snipped]
> text/plain is being compared, and the text/plain of your objects include a random memory address
OK, this all makes sense.   I'll have a play with nbval, and if I need to come back with patches.

Going to close this for now, since I probably need to use nbval a bit before coming back with any suggestions / patches.

Cheers for the help.

**Comment by vidartf** [comment]
Alright, feel free to comment/reopen as you see appropriate :)
