### ISSUE TITLE
Option to select only notebook tests

### ISSUE THREAD

**Issue by gasparka** [computationalmodelling/nbval#99]
The `pytest --nbval` picks all the tests it finds. It would be useful to have an option to select only the notebooks. I found some ways to do this via .cfg file, but command line option would be better.
Ideas?

**Comment by vidartf** [comment]
You could skip python tests with the flags `-p no:python`, i.e. in full `py.test -p no:python --nbval`.

**Comment by vidartf** [comment]
Ref https://docs.pytest.org/en/latest/usage.html#disabling-plugins

**Comment by takluyver** [comment]
I think it could be added to the README.
